### ISSUE TITLE
Unable to change mode

### ISSUE THREAD

**Issue by shalzz** [pop-os/gnome-shell-extension-system76-power#14]
**Distribution (run `cat /etc/os-release`):**
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
master branch

**Issue/Bug Description:**
Toggling the profile in the menu changes it only in the menu but does not reflect with the system76-power daemon.

Log:
`dbus-broker[779]: A security policy denied :1.1974 to send method call /com/system76/PowerDaemon:com.system76.PowerDaemon.Battery to :1.1366.`

**Comment by mmstick** [comment]
> Arch Linux

You may want to bring this up with the maintainer of the system76-power package. It might not be installing the policy file.

**Comment by jcsanyi** [comment]
If anybody finds this in the future, check the contents of /usr/share/dbus-1/system.d/system76-power.conf and make sure your user is a member of one of the groups that is authorized there. Specifically, adding my user to the "adm" group fixed this for me.
