### ISSUE TITLE
Active profile does not update when changed from command line

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-shell-extension-system76-power#15]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 18.04 
 
**Issue/Bug Description:**
When switching system76-power profiles from the command line, (ie. `system76-power profile battery` when previously in balanced mode) the gnome shell extension does not update which profile is active.

**Steps to reproduce (if you know):**
1. Change profile from command line
2. Check shell extension

**Expected behavior:**
Shell extension should update when changes are made from the command line.

**Comment by mmstick** [comment]
Requires https://github.com/pop-os/system76-power/pull/63
