### ISSUE TITLE
Support graphics switching without reboot

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-shell-extension-system76-power#34]
With https://github.com/pop-os/system76-power/pull/119/ good to go, the shell extension should be updated to support this new method of graphics switching.

The copy will also need to change to state that switching graphics will require restarting GDM (logging out and back in).

**Comment by crawfxrd** [comment]
> Because this can't be implemented cleanly (must kill all X sessions), we're going to keep requiring a reboot.
