### ISSUE TITLE
20.04: Switchable graphics option not available

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-shell-extension-system76-power#36]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-shell-extension-system76-power
system76-power

**Issue/Bug Description:**
On the addw1 and oryp5(and I assume the gaze14), switchable graphics options are not available from the GNOME shell extension. I am able to switch graphics modes with system76-power from the command line.

Journald shows the following error:

`gnome-shell[1750]: gnome-shell-extension-system76-power: failed to detect graphics switching: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?`

**Comment by jackpot51** [comment]
Can confirm on gaze14

**Comment by leviport** [comment]
Same on addw1

**Comment by mmstick** [comment]
Should be fixed with cf8d38d

**Comment by jackpot51** [comment]
Thanks @mmstick !

**Comment by leviport** [comment]
I just gave it a test, and the extension is now showing graphics options on addw1, but clicking them does not initiate a graphics change.

**Comment by leviport** [comment]
It's good now.
