### ISSUE TITLE
Support GNOME 40

### ISSUE THREAD

**Issue by qx-775** [pop-os/gnome-shell-extension-system76-power#57]
Hi, currently this extension is currently incompatible with GNOME 40. Will this be implemented?

For instance I am on Arch Linux where this shell extensions can't be run. Knowing that ofcourse pop os will not upgrade to gnome 40 for a while. I am just curious if this will be implemented before october 2021 (i believe, at pop os 21.04).

Don't feel pressure to develop, just curious.

**Comment by Albonycal** [comment]
Any updates ?

**Comment by jackpot51** [comment]
I've been using this on GNOME 40, what issues are you having?

**Comment by jacobgkau** [comment]
The metadata.json file was updated in late May, a while after this issue was opened: https://github.com/pop-os/gnome-shell-extension-system76-power/pull/60
