### ISSUE TITLE
[bug] Hybrid Graphics broken on mainline kernels

### ISSUE THREAD

**Issue by aarron-lee** [pop-os/gnome-shell-extension-system76-power#59]
**Distribution:**
 
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
``` 

**Issue/Bug Description:**

System76 Power doesn't work properly on mainline kernels 5.11.17 and higher. Works fine on 5.11.16

  - personally tested this with mainline kernels 5.11.17,  5.11.19, and 5.12.2.
  - 5.11.16 and lower all worked fine for me

**Steps to reproduce (if you know):**

1. update kernel to mainline 5.11.17 or higher
2. select `Hybrid Graphics` option via System76 Power
3. reboot machine
4. System76 Power is stuck on `Integrated Graphics` after reboot.
5. right click + `Launch using Discrete Graphics Card` option is missing

**Expected behavior:**

- System76 Power properly changes between integrated, hybrid, etc
- right click + `Launch using Discrete Graphics Card` option is present and working

**Comment by mmstick** [comment]
On what kind of system was this replicated?

**Comment by aarron-lee** [comment]
> On what kind of system was this replicated?

This is on an ASUS Zephyrus G15 laptop with Ryzen 5900hs + NVIDIA GTX 3060.

This isn't a System76 laptop, so I'm not really expecting any support, just reporting the bug.

**Comment by aarron-lee** [comment]
Ah, just realized that I should've probably posted the issue at https://github.com/pop-os/system76-power instead
