### ISSUE TITLE
Documentation for differences between profiles

### ISSUE THREAD

**Issue by 31337-4554551n** [pop-os/gnome-shell-extension-system76-power#66]
I would like to request some documentation in the differences between battery life, balanced, and high performance profiles for the readme please.
It's very difficult (and I still haven't been able to) to get information on what the actual changes made by these profiles are, with the exception of brightness which is obvious when they are selected.
Also, if/how they interact/interfere with tlp/powertop

**Comment by jacobgkau** [comment]
This would probably belong in https://github.com/pop-os/system76-power/#readme. The GNOME Shell extension is just a frontend, it does not define the profiles.

**Comment by 31337-4554551n** [comment]
Fair point, thank you
