### ISSUE TITLE
Slows extremly down in Hybrid-Mode on external monitor (NVIDIA)

### ISSUE THREAD

**Issue by aliceTheGrinseCatz** [pop-os/gnome-shell-extension-system76-power#69]
**Distribution (run `cat /etc/os-release`):**

Pop!_OS 20.10, 21.04 & 21.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

gnome-shell-extensions-system76-power 2.0.2~1631828901~21.10~a901dc0
gnome 1:40+1

**Issue/Bug Description:**

If the display settings is set to Single Display and an external Monitor to primary monitor, so, the internal monitor isn't use, GNOME and all GUI applications are extreme slow. The cursor can be move fastly, but hovering animations as well as the reaction on click events are extreme delayed for some reasons. This bug cannot be solved with logout or reboot and can only be replicated in Hybrid Mode in Single Display to external monitor and only while logged in. Dupplication or Extended Display doesn't has the bug what's really weird because using internal and external monitor has no slowdown. Also, the NVIDIA mode doesn't have this problem in Single Display too. Shouldn't the Hybrid Mode always use the NVIDIA graphics automatically for the external monitor?

**Steps to reproduce (if you know):**

Switch to Hyrid Mode and restart.
Login again and set the display settings to Single Display and an external display to Primary Display.

**Expected behavior:**

Hyrbid Mode doesn't slow down.

**Other Notes:**

Used device: System76 Oryx Pro (oryp6) with Intel i10-875H, 2 * 8 GB DDR4-RAM, Intel UHD plus NVIDIA GeForce RTX 2060
Tested port: HDMI, USB-C Thunderbold via Hub with HDMI

**Comment by leviport** [comment]
Thanks for the report. We are tracking this issue here: https://github.com/pop-os/nvidia-graphics-drivers/issues/61
