### ISSUE TITLE
Power extension presents no menu option on Arch Linux

### ISSUE THREAD

**Issue by taohansen** [pop-os/gnome-shell-extension-system76-power#7]
**Distribution (run `cat /etc/os-release`):**
Both:
* Arch Linux updated as of June 10th
* Pop!_OS 18.04

**Issue/Bug Description:**
ThinkPad P50 with Nvidia M2000M discrete graphics. Both with nouveau/modesetting and nvidia/modesetting drivers the power management menu doesn't present itself in the top-right menu of GNOME. 

This is across both the official Pop!_OS distro and Arch Linux.

**Steps to reproduce (if you know):**
If running any distro other than Pop!_OS
```
git clone {repo}
cd {repo}
make
make install
sudo systemctl reboot

```

**Comment by jackpot51** [comment]
Do you have system76-power installed as well?

**Comment by taohansen** [comment]
```
$ system76-power daemon
Starting daemon
Rescanning PCI bus
0000:00:02.0: Intel graphics
0000:01:00.0: NVIDIA graphics
Setting automatic graphics power
Enabling graphics power
Connecting to dbus system bus
Registering dbus name com.system76.PowerDaemon
Adding dbus path /com/system76/PowerDaemon with interface com.system76.PowerDaemon
Handling dbus requests
```
Running the daemon still doesn't give me access to the GNOME Shell power menu.

**Comment by taohansen** [comment]
After installing tlp and acpi_call, I now have full access to the menu.
