### ISSUE TITLE
Not able to switch graphics Intel to Invidia

### ISSUE THREAD

**Issue by fredsco** [pop-os/gnome-shell-extension-system76-power#73]
**Distribution (run `cat /etc/os-release`):**
 
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

pt policy $PACKAGE_NAME                                  ok  4s  17:59:45 
Package files:
 100 /var/lib/dpkg/status
     release a=now
1001 http://ppa.launchpad.net/system76-dev/stable/ubuntu impish/main i386 Packages
     release v=21.10,o=LP-PPA-system76-dev-stable,a=impish,n=impish,l=System76 Stable PPA,c=main,b=i386
     origin ppa.launchpad.net
1001 http://ppa.launchpad.net/system76-dev/stable/ubuntu impish/main amd64 Packages
     release v=21.10,o=LP-PPA-system76-dev-stable,a=impish,n=impish,l=System76 Stable PPA,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/smoser/bluetooth/ubuntu impish/main amd64 Packages
     release v=21.10,o=LP-PPA-smoser-bluetooth,a=impish,n=impish,l=bluetooth updates,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu impish/main i386 Packages
     release v=21.10,o=LP-PPA-pipewire-debian-pipewire-upstream,a=impish,n=impish,l=PipeWire Upstream,c=main,b=i386
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu impish/main amd64 Packages
     release v=21.10,o=LP-PPA-pipewire-debian-pipewire-upstream,a=impish,n=impish,l=PipeWire Upstream,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/linuxuprising/apps/ubuntu impish/main i386 Packages
     release v=21.10,o=LP-PPA-linuxuprising-apps,a=impish,n=impish,l=Extra Ubuntu / Linux Mint Applications,c=main,b=i386
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/linuxuprising/apps/ubuntu impish/main amd64 Packages
     release v=21.10,o=LP-PPA-linuxuprising-apps,a=impish,n=impish,l=Extra Ubuntu / Linux Mint Applications,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/linrunner/tlp/ubuntu impish/main i386 Packages
     release v=21.10,o=LP-PPA-linrunner-tlp,a=impish,n=impish,l=TLP,c=main,b=i386
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/linrunner/tlp/ubuntu impish/main amd64 Packages
     release v=21.10,o=LP-PPA-linrunner-tlp,a=impish,n=impish,l=TLP,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/jlbarriere68/noson-app/ubuntu impish/main amd64 Packages
     release v=21.10,o=LP-PPA-jlbarriere68-noson-app,a=impish,n=impish,l=noson-app,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu impish/main i386 Packages
     release v=21.10,o=LP-PPA-graphics-drivers,a=impish,n=impish,l=Proprietary GPU Drivers,c=main,b=i386
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu impish/main amd64 Packages
     release v=21.10,o=LP-PPA-graphics-drivers,a=impish,n=impish,l=Proprietary GPU Drivers,c=main,b=amd64
     origin ppa.launchpad.net
 500 https://dl.google.com/linux/chrome/deb stable/main amd64 Packages
     release v=1.0,o=Google LLC,a=stable,n=stable,l=Google,c=main,b=amd64
     origin dl.google.com
 500 http://ppa.launchpad.net/cappelikan/ppa/ubuntu impish/main amd64 Packages
     release v=21.10,o=LP-PPA-cappelikan,a=impish,n=impish,l=PPA for cappelikan,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/blaze/rtbth-dkms/ubuntu impish/main amd64 Packages
     release v=21.10,o=LP-PPA-blaze-rtbth-dkms,a=impish,n=impish,l=rtbth dkms,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/agornostal/ulauncher/ubuntu impish/main i386 Packages
     release v=21.10,o=LP-PPA-agornostal-ulauncher,a=impish,n=impish,l=Ulauncher,c=main,b=i386
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/agornostal/ulauncher/ubuntu impish/main amd64 Packages
     release v=21.10,o=LP-PPA-agornostal-ulauncher,a=impish,n=impish,l=Ulauncher,c=main,b=amd64
     origin ppa.launchpad.net
 500 https://downloads.1password.com/linux/debian/amd64 stable/main amd64 Packages
     release o=. stable,a=stable,n=stable,l=. stable,c=main,b=amd64
     origin downloads.1password.com
 500 https://nl.mirrors.clouvider.net/ubuntu impish-security/multiverse i386 Packages
     release v=21.10,o=Ubuntu,a=impish-security,n=impish,l=Ubuntu,c=multiverse,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-security/multiverse amd64 Packages
     release v=21.10,o=Ubuntu,a=impish-security,n=impish,l=Ubuntu,c=multiverse,b=amd64
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-security/universe i386 Packages
     release v=21.10,o=Ubuntu,a=impish-security,n=impish,l=Ubuntu,c=universe,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-security/universe amd64 Packages
     release v=21.10,o=Ubuntu,a=impish-security,n=impish,l=Ubuntu,c=universe,b=amd64
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-security/restricted i386 Packages
     release v=21.10,o=Ubuntu,a=impish-security,n=impish,l=Ubuntu,c=restricted,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-security/restricted amd64 Packages
     release v=21.10,o=Ubuntu,a=impish-security,n=impish,l=Ubuntu,c=restricted,b=amd64
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-security/main i386 Packages
     release v=21.10,o=Ubuntu,a=impish-security,n=impish,l=Ubuntu,c=main,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-security/main amd64 Packages
     release v=21.10,o=Ubuntu,a=impish-security,n=impish,l=Ubuntu,c=main,b=amd64
     origin nl.mirrors.clouvider.net
 100 https://nl.mirrors.clouvider.net/ubuntu impish-backports/universe i386 Packages
     release v=21.10,o=Ubuntu,a=impish-backports,n=impish,l=Ubuntu,c=universe,b=i386
     origin nl.mirrors.clouvider.net
 100 https://nl.mirrors.clouvider.net/ubuntu impish-backports/universe amd64 Packages
     release v=21.10,o=Ubuntu,a=impish-backports,n=impish,l=Ubuntu,c=universe,b=amd64
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-updates/multiverse i386 Packages
     release v=21.10,o=Ubuntu,a=impish-updates,n=impish,l=Ubuntu,c=multiverse,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-updates/multiverse amd64 Packages
     release v=21.10,o=Ubuntu,a=impish-updates,n=impish,l=Ubuntu,c=multiverse,b=amd64
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-updates/universe i386 Packages
     release v=21.10,o=Ubuntu,a=impish-updates,n=impish,l=Ubuntu,c=universe,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-updates/universe amd64 Packages
     release v=21.10,o=Ubuntu,a=impish-updates,n=impish,l=Ubuntu,c=universe,b=amd64
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-updates/restricted i386 Packages
     release v=21.10,o=Ubuntu,a=impish-updates,n=impish,l=Ubuntu,c=restricted,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-updates/restricted amd64 Packages
     release v=21.10,o=Ubuntu,a=impish-updates,n=impish,l=Ubuntu,c=restricted,b=amd64
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-updates/main i386 Packages
     release v=21.10,o=Ubuntu,a=impish-updates,n=impish,l=Ubuntu,c=main,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish-updates/main amd64 Packages
     release v=21.10,o=Ubuntu,a=impish-updates,n=impish,l=Ubuntu,c=main,b=amd64
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish/multiverse i386 Packages
     release v=21.10,o=Ubuntu,a=impish,n=impish,l=Ubuntu,c=multiverse,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish/multiverse amd64 Packages
     release v=21.10,o=Ubuntu,a=impish,n=impish,l=Ubuntu,c=multiverse,b=amd64
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish/universe i386 Packages
     release v=21.10,o=Ubuntu,a=impish,n=impish,l=Ubuntu,c=universe,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish/universe amd64 Packages
     release v=21.10,o=Ubuntu,a=impish,n=impish,l=Ubuntu,c=universe,b=amd64
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish/restricted i386 Packages
     release v=21.10,o=Ubuntu,a=impish,n=impish,l=Ubuntu,c=restricted,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish/restricted amd64 Packages
     release v=21.10,o=Ubuntu,a=impish,n=impish,l=Ubuntu,c=restricted,b=amd64
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish/main i386 Packages
     release v=21.10,o=Ubuntu,a=impish,n=impish,l=Ubuntu,c=main,b=i386
     origin nl.mirrors.clouvider.net
 500 https://nl.mirrors.clouvider.net/ubuntu impish/main amd64 Packages
     release v=21.10,o=Ubuntu,a=impish,n=impish,l=Ubuntu,c=main,b=amd64
     origin nl.mirrors.clouvider.net
Pinned packages:

**Issue/Bug Description:**

I am not able to switch to Nvidia graphics.. I do not get any errors at all when switching but after the mandatory reboot it's still using intel graphics..

**Steps to reproduce (if you know):**

1. click on the battery icon to open the gnome extension,
2. Press NVIDIA Graphics
3. wait and restart computer

**Expected behavior:**

Computer should switch to NVIDIA, os settings should not show intel graphics being used but NVIDIA. and NVIDIA-SMI command should be working..

**Other Notes:**

I am using Wayland FYI
GNOME 40.4.0

**Comment by jacobgkau** [comment]
Does it work if you run `system76-power graphics nvidia` in a terminal? If not, this issue should probably be moved to https://github.com/pop-os/system76-power.

What hardware and what kernel version are you using?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by fredsco** [comment]
I found out the issue! Apparently the driver was blacklisted.. (see image attached) This should perhaps be in the installation docs!
![blacklist-nvidia](https://user-images.githubusercontent.com/14234528/157718106-243f3973-778f-47a7-8527-7d0fc9ec371f.png)
